server:
  port: 8080

spring:
  application:
    name: payfone-excel-processor
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

payfone:
  api:
    base-url: https://edlpayfoneupsertservice.app.uat.pcf.syfbank.com
    endpoint: /payfoneupsert/insertPayfoneRecord
    event-name: PayfoneDataService.JavaAPI.Insert
    server-name: 10.245.345
    action: insert
    version:
      major: 1
      minor: 1
      patch: 0
    defaults:
      line-type: Mobile
      carrier: T-Mobile USA
      country-code: US
      verified: TRUE
      name-score: 100
      address-score: -1
      event-type: TN_PORT
      ssn: 123456789
      dob: 1970-01-01
      lexid: 123456
      syfid: GUIUSER
      tokenid: GUIUSERToken
      clientid: F10SAMCO
      sys: 0000
      agent: 0000
      default-account-number: 123456789
      channel-id: Default

logging:
  level:
    com.syf.payfone: DEBUG